In [1]:
import numpy as np

In [2]:
X = np.array([1., .5])
W1 = np.array([[.1, .3, .5], [.2, .4, .6]])
B1 = np.array([.1, .2, .3])

print(W1.shape)
print(X.shape)
print(B1.shape)


(2, 3)
(2,)
(3,)


In [3]:
A1 = np.dot(X, W1) + B1

In [4]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [5]:
Z1 = sigmoid(A1)

In [6]:
print(A1)
print(Z1)

[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]


In [7]:
W2 = np.array([[.1, .4], [.2, .5], [.3, .6]])
B2 = np.array([.1, .2])

print(Z1.shape)
print(W2.shape)
print(B2.shape)

(3,)
(3, 2)
(2,)


In [8]:
print(Z1)
print(W2)

[0.57444252 0.66818777 0.75026011]
[[0.1 0.4]
 [0.2 0.5]
 [0.3 0.6]]


In [10]:
A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)

In [11]:
def identity_function(x):
    # 恒等関数
    return x

In [12]:
W3 = np.array([[.1, .3], [.2, .4]])
B3 = np.array([.1, .2])

A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3)

3層ニューラルネットのまとめ

In [13]:
def init_network():
    network = {}
    network["W1"] = np.array([[.1, .3, .5], [.2, .4, .6]])
    network["b1"] = np.array([.1, .2, .3])
    network["W2"] = np.array([[.1, .4], [.2, .5], [.3, .6]])
    network["b2"] = np.array([.1, .2])
    network["W3"] = np.array([[.1, .3], [.2, .4]])
    network["b3"] = np.array([.1, .2])

    return network

In [16]:
def forward(network, x):
    W1, W2, W3 = network["W1"], network["W2"], network["W3"]
    b1, b2, b3 = network["b1"], network["b2"], network["b3"]

    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    Y = identity_function(a3)
    return Y

In [18]:
def softmax(x):
    c = np.max(x) # avoid overflow
    y = np.exp(x-c)/np.sum(np.exp(x-c))
    return y